/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Airliner;
import Business.Fleet;
import Business.TravelAgency;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class bookpanel extends javax.swing.JPanel {

    /**
     * Creates new form book panel
     */
    private TravelAgency TA;
    private JPanel rightPanel;
    public bookpanel(JPanel rightPanel,TravelAgency TA) {
       this.TA=TA;
       this.rightPanel=rightPanel;
       initComponents();
    }
        
    public JTextField getDatefield() {
        return datefield;
    }

    public void setDatefield(JTextField datefield) {
        this.datefield = datefield;
    }

    public JTable getDetailsTable() {
        return detailsTable;
    }

    public void setDetailsTable(JTable detailsTable) {
        this.detailsTable = detailsTable;
    }

    public JTextField getFromfield() {
        return fromfield;
    }

    public void setFromfield(JTextField fromfield) {
        this.fromfield = fromfield;
    }

    public JTextField getTofield() {
        return tofield;
    }

    public void setTofield(JTextField tofield) {
        this.tofield = tofield;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fromfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tofield = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        jLabel1.setText("From:");

        jLabel2.setText("To:");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner", "Flight", "From", "to", "date"
            }
        ));
        jScrollPane1.setViewportView(detailsTable);

        jLabel3.setText("Date:");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fromfield, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tofield, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(searchButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nextButton)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fromfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(jLabel3)
                    .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if(fromfield.getText().equals("") || tofield.getText().equals("") || datefield.getText().equals(""))
        {
           JOptionPane.showMessageDialog(null, "fields cannot be empty"); 
        }
        else
        {
        String From=fromfield.getText();
        String To=tofield.getText();
        Date ddate = null;
        try{
             ddate=Date.valueOf(datefield.getText());
             String date=String.valueOf(ddate);             
            populate(From,To,date);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Date must be in the format YYYY-DD-MM");
        }
        
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        int selectedrow=detailsTable.getSelectedRow();
            if(selectedrow>=0)
               {
                  Fleet fleet=(Fleet)detailsTable.getValueAt(selectedrow, 1);
                  Airliner air=(Airliner)detailsTable.getValueAt(selectedrow, 0);
                  booking bookpanel=new booking(rightPanel,fleet,TA,air);
                  rightPanel.add("bookPanel", bookpanel);
                  CardLayout layout=(CardLayout)rightPanel.getLayout();
                  layout.next(rightPanel);
               }
            else
                {
                 JOptionPane.showMessageDialog(null, "Please select a row");
                }

    }//GEN-LAST:event_nextButtonActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
       rightPanel.remove(this);
       CardLayout layout = (CardLayout)rightPanel.getLayout();
       layout.previous(rightPanel);
    }//GEN-LAST:event_backbtnActionPerformed
public void populate(String src,String dest,String date)
{   
    DefaultTableModel dtm = (DefaultTableModel)detailsTable.getModel();
    dtm.setRowCount(0);
    for(Airliner air : TA.getAirArrayList())
        {
            for(Fleet fleet : air.getfArrayList())
            {
                if(fleet.getSchedule().getSrc().equals(src) && fleet.getSchedule().getDest().equals(dest) && fleet.getSchedule().getDate().toString().equals(date))
                {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=air;
                row[1]=fleet;
                row[2]=fleet.getSchedule().getSrc();
                row[3]=fleet.getSchedule().getDest();
                row[4]=fleet.getSchedule().getDate();
                dtm.addRow(row);
                }
            }
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField datefield;
    private javax.swing.JTable detailsTable;
    private javax.swing.JTextField fromfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField tofield;
    // End of variables declaration//GEN-END:variables
}
