/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class Bookorcreate extends javax.swing.JPanel {

    /**
     * Creates new form Bookorcreate
     */
    private TravelAgency TA;
    private JPanel rightPanel ;
    public Bookorcreate(JPanel rightPanel,TravelAgency TA) {
        this.TA=TA;
        this.rightPanel=rightPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        bookhistorybtn = new javax.swing.JButton();

        bookButton.setText("Book Ticket");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add Customer");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        bookhistorybtn.setText("Booking History");
        bookhistorybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookhistorybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(bookButton)
                .addGap(18, 18, 18)
                .addComponent(bookhistorybtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(bookButton)
                    .addComponent(bookhistorybtn))
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        bookpanel bookpanel=new bookpanel(rightPanel,TA);
        rightPanel.add("bookPanel", bookpanel);
        CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_bookButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddCustomer addcustomer=new AddCustomer(rightPanel,TA);
        rightPanel.add("addcustomer", addcustomer);
        CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_addButtonActionPerformed

    private void bookhistorybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookhistorybtnActionPerformed
        bookinghistorypnl bhispnl=new bookinghistorypnl(rightPanel,TA);
        rightPanel.add("bhispnl", bhispnl);
        CardLayout layout=(CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
        
    }//GEN-LAST:event_bookhistorybtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton bookButton;
    private javax.swing.JButton bookhistorybtn;
    // End of variables declaration//GEN-END:variables
}
